/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package butonoyunu;

import java.util.Random;
import java.util.Scanner;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JButton;
/**
 *
 * @author Bogdanovic44
 */
public class ButonOyunu extends javax.swing.JFrame {
    String ifade;
    String sayilar[]={"","1","2","3","4","5","6","7","8"};
    
    /**
     * Creates new form ButonOyunu
     */
    public ButonOyunu() {
        initComponents();
        karistir();
        zamanSureci();
    }
    
    static int interval=60;
    static Timer timer;
    
    public void zamanSureci(){
        int delay = 1000;
        int period = 1000;
        timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
          
            public void run() {
                jLabel2.setText(String.valueOf(setInterval()));

            }
        }, delay, period);
    }

    private final int setInterval() {
        JButton[] btn={jButton1,jButton2,jButton3,jButton4,jButton5,jButton6,jButton7,jButton8,jButton9};
        if (interval == 1){
            timer.cancel();
            for (int i = 0; i < btn.length; i++) {
                btn[i].setEnabled(false);
            }
            jLabel1.setText("Üzgünüz, süre bitti");
            jLabel1.setVisible(true);
        }
        return --interval;
    }
    
    public void karistir(){
        JButton[] btn={jButton1,jButton2,jButton3,jButton4,jButton5,jButton6,jButton7,jButton8,jButton9};
        Random r=new Random();
        for (int i = 0; i < btn.length; i++) {
            int fix=r.nextInt(9);
            if(btn[fix].getText()==""){
                btn[fix].setText(sayilar[i]);
            }
            else{
                i--;
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number Game");

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(50, 50, 50)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JButton b=(JButton)evt.getSource();
        if(jButton1.getText()==""){
           if(b==jButton2){
               jButton1.setText(jButton2.getText());
               jButton2.setText("");
           }
           else if(b==jButton4){
               jButton1.setText(jButton4.getText());
               jButton4.setText("");   
           }
        }
        else if(jButton2.getText()==""){
           if(b==jButton1){
               jButton2.setText(jButton1.getText());
               jButton1.setText("");
           }
           else if(b==jButton3){
               jButton2.setText(jButton3.getText());
               jButton3.setText("");
           }
           else if(b==jButton5){
               jButton2.setText(jButton5.getText());
               jButton5.setText("");
           }
        }
        else if(jButton3.getText()==""){
           if(b==jButton2){
               jButton3.setText(jButton2.getText());
               jButton2.setText("");
           }
           else if(b==jButton6){
               jButton3.setText(jButton6.getText());
               jButton6.setText("");
           }
        }
        else if(jButton4.getText()==""){
           if(b==jButton1){
               jButton4.setText(jButton1.getText());
               jButton1.setText("");
           }
           else if(b==jButton5){
               jButton4.setText(jButton5.getText());
               jButton5.setText("");
           }
           else if(b==jButton7){
               jButton4.setText(jButton7.getText());
               jButton7.setText("");
           }
        }
        else if(jButton5.getText()==""){
           if(b==jButton2){
               ifade=jButton2.getText();
               jButton2.setText("");
               jButton5.setText(ifade);
           }
           else if(b==jButton4){
               ifade=jButton4.getText();
               jButton4.setText("");
               jButton5.setText(ifade);
           }
           else if(b==jButton6){
               ifade=jButton6.getText();
               jButton6.setText("");
               jButton5.setText(ifade);
           }
           else if(b==jButton8){
               ifade=jButton8.getText();
               jButton8.setText("");
               jButton5.setText(ifade);
           }
        }
        else if(jButton6.getText()==""){
           if(b==jButton3){
               ifade=jButton3.getText();
               jButton3.setText("");
               jButton6.setText(ifade);
           }
           else if(b==jButton5){
               ifade=jButton5.getText();
               jButton5.setText("");
               jButton6.setText(ifade);
           }
           else if(b==jButton9){
               ifade=jButton9.getText();
               jButton9.setText("");
               jButton6.setText(ifade);
               if(jButton1.getText()=="1"&&jButton2.getText()=="2"&&jButton3.getText()=="3"&&
                  jButton4.getText()=="4"&&jButton5.getText()=="5"&&jButton6.getText()=="6"&&
                  jButton7.getText()=="7"&&jButton8.getText()=="8"){
                   jLabel1.setText("TEBRİKLER!!!");
               }
           }
        }
        else if(jButton7.getText()==""){
           if(b==jButton4){
               ifade=jButton4.getText();
               jButton4.setText("");
               jButton7.setText(ifade);
           }
           else if(b==jButton8){
               ifade=jButton8.getText();
               jButton8.setText("");
               jButton7.setText(ifade);
           }
        }
        else if(jButton8.getText()==""){
           if(b==jButton5){
               ifade=jButton5.getText();
               jButton5.setText("");
               jButton8.setText(ifade);
           }
           else if(b==jButton7){
               ifade=jButton7.getText();
               jButton7.setText("");
               jButton8.setText(ifade);
           }
           else if(b==jButton9){
               ifade=jButton9.getText();
               jButton9.setText("");
               jButton8.setText(ifade);
               if(jButton1.getText()=="1"&&jButton2.getText()=="2"&&jButton3.getText()=="3"&&
                  jButton4.getText()=="4"&&jButton5.getText()=="5"&&jButton6.getText()=="6"&&
                  jButton7.getText()=="7"&&jButton8.getText()=="8"){
                   jLabel1.setText("TEBRİKLER!!!");
               }
           }
        }
        else if(jButton9.getText()==""){
            if(b==jButton6){
               ifade=jButton6.getText();
               jButton6.setText("");
               jButton9.setText(ifade);
            }
            else if(b==jButton8){
               ifade=jButton8.getText();
               jButton8.setText("");
               jButton9.setText(ifade);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ButonOyunu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ButonOyunu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ButonOyunu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ButonOyunu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ButonOyunu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
